Name: Continous Deployment

on:
  push:
    branches:
      - master

job:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: "say hello"
        run: |
          echo "deployig to master branch"
