name: Continous Integration

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to dev
        run: |
          echo deploying to dev
          echo deploying to stg too