Name: Continous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - name: deploy to dev
        run: |
          echo deploying to dev