name: Secrets testing

on: [push]
env:
  day_of_week: monday

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: say hello
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: sreenivas