name: Secrets testing

on: [push]
env:
  DAY_OF_WEEK: monday

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: "say hello"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: ${{ secrets.FIRSTNAME }}