name: Secrets testing

on: [push]

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: read secret variable
        run: |
          echo "this is first secret: ${{ secrets.FIRST_SECRET }}"