name: Secrets testing

on: [push]

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "$FIRST_SECRET"
        env:
          FIRST_SECRET: ${{ secrets.FIRST_SECRET }}