name: Secrets testing

on: [push]

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.FIRST_SECRET }}
        run: |
          echo "$SUPER_SECRET"