name: My first github actions

on: [pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.actor }}"
      - name: checkout the repo
        uses: actions/checkout@v1
      - name: List files
        run: |
          pwd
          ls -la
#      - name: first action
#        id: greet
#        uses: actions/hello-world-javascript-action@v1.1
#        with:
#          who-to-greet: sreeni
#      - name: output from greet
#        run: echo "${{ steps.greet.outputs.time}}"

