name: My first github actions

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -la
      - name: first action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: sreeni
      - name: output from greet
        run: echo "${{ steps.greet.outputs.time}}"

